# -*- coding: utf-8 -*-
"""analyze stock data and building dashboard.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-CRPucK02PuZg0vBFStELeqbVpgw-qVW
"""

import yfinance as yf
import pandas as pd

#create an object for AAPL (Apple)
apple = yf.Ticker("AAPL")

# get historical market data
apple_data=apple.history(period="max")

apple_data.reset_index(inplace=True)

#create an object for AMD (Advanced Micro Devices)
amd=yf.Ticker("AMD")

amd_data=amd.history(period="max")

amd_data.reset_index(inplace=True)

#Extracting Stock Data Using a Web Scraping BeautifulSoup